/**
 * Outbound worker preparation.
 *
 * For each namespace with an outbound configured at startup:
 *   1. Copy the user-authored outbound script to `<root>/outbound/<ns>/user-outbound.mjs`
 *   2. Write a generated `bridge.mjs` alongside it that:
 *      - reads `X-WFP-Outbound` header from the user worker's outbound `fetch()`
 *      - filters by allow-list (`env.__WFP_ALLOWED_PARAMS`)
 *      - calls user-outbound's `default.fetch(req, env, ctx)` with the projected env
 *
 * The user worker side: a per-tenant wrapper module (generated at config time
 * by buildMfConfig in sim.ts) intercepts inbound requests, runs user code in
 * `als.run(outboundParams)`, and patches `globalThis.fetch` to re-attach the
 * header on every subrequest. AsyncLocalStorage requires the `nodejs_als` (or
 * `nodejs_compat`) flag — buildMfConfig adds it automatically when outbound is
 * configured.
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import type { Binding } from './types.js';

export interface OutboundConfigInternal {
  scriptPath: string;
  parameters?: string[];
  bindings?: Binding[];
}

export interface PreparedOutbound {
  ns: string;
  /** Directory containing both bridge.mjs and user-outbound.mjs. */
  dir: string;
  parameters: string[];
  bindings: Binding[];
}

export async function prepareOutbounds(
  rootDir: string,
  outbounds: Record<string, OutboundConfigInternal> | undefined,
): Promise<PreparedOutbound[]> {
  if (!outbounds) return [];
  const out: PreparedOutbound[] = [];
  for (const [ns, cfg] of Object.entries(outbounds)) {
    const dir = path.resolve(rootDir, sanitizeFs(ns));
    await fs.mkdir(dir, { recursive: true });

    const userPath = path.join(dir, 'user-outbound.mjs');
    await fs.copyFile(cfg.scriptPath, userPath);

    const bridgePath = path.join(dir, 'bridge.mjs');
    await fs.writeFile(bridgePath, BRIDGE_SOURCE);

    out.push({
      ns, dir,
      parameters: cfg.parameters ?? [],
      bindings: cfg.bindings ?? [],
    });
  }
  return out;
}

function sanitizeFs(s: string): string {
  const cleaned = s.replace(/[^A-Za-z0-9_.-]/g, '_');
  // Never let a name collapse to a path-traversal or empty directory segment.
  return cleaned === '' || cleaned === '.' || cleaned === '..' ? '_' : cleaned;
}

const BRIDGE_SOURCE = `// AUTO-GENERATED by cf-wfp-simulator. Do not edit.
// Outbound bridge: reads x-wfp-outbound header (set by per-tenant wrapper),
// filters by allow-list, projects onto env, calls user outbound module.

import userOutbound from './user-outbound.mjs';

const HEADER = 'x-wfp-outbound';

function parseAllowList(env) {
  try {
    const v = JSON.parse(env.__WFP_ALLOWED_PARAMS ?? '[]');
    return Array.isArray(v) ? v.filter(x => typeof x === 'string') : [];
  } catch { return []; }
}

function parseParams(raw) {
  if (!raw) return {};
  try {
    const v = JSON.parse(raw);
    return v && typeof v === 'object' && !Array.isArray(v) ? v : {};
  } catch { return {}; }
}

export default {
  async fetch(request, env, ctx) {
    if (typeof userOutbound?.fetch !== 'function') {
      return new Response('outbound-bridge: user outbound has no default.fetch', { status: 500 });
    }
    const allowed = parseAllowList(env);
    const params = parseParams(request.headers.get(HEADER));
    const projected = {};
    for (const k of allowed) if (k in params) projected[k] = params[k];

    // Strip control header before user code sees it.
    const cleanHeaders = new Headers(request.headers);
    cleanHeaders.delete(HEADER);
    const cleanReq = new Request(request.url, {
      method: request.method,
      headers: cleanHeaders,
      body: request.body,
      duplex: request.body ? 'half' : undefined,
      redirect: 'manual',
    });

    // Synthesize env: user outbound's bindings + projected params (params win on collision).
    const synthEnv = { ...env, ...projected };
    delete synthEnv.__WFP_ALLOWED_PARAMS;
    return userOutbound.fetch(cleanReq, synthEnv, ctx);
  },
};
`;

/**
 * Per-tenant wrapper template — referenced from sim.ts buildMfConfig.
 * The generated wrapper imports the user's main module by relative path (which
 * matches the metadata.main_module value, copied verbatim alongside it in dir).
 */
export function renderWrapper(userMainBasename: string): string {
  // Defensive: escape any quote chars in the filename (very unlikely but cheap).
  const esc = JSON.stringify('./' + userMainBasename);
  return `// AUTO-GENERATED by cf-wfp-simulator. Do not edit.
// Per-tenant ALS wrapper. Threads X-WFP-Outbound from inbound -> all subrequest
// fetches via AsyncLocalStorage. Requires the nodejs_als compat flag (added
// automatically when an outbound is configured for this namespace).

import { AsyncLocalStorage } from 'node:async_hooks';
import user from ${esc};

const HEADER = 'x-wfp-outbound';
const als = new AsyncLocalStorage();

const origFetch = globalThis.fetch.bind(globalThis);
Object.defineProperty(globalThis, 'fetch', {
  configurable: true, writable: true,
  value: (input, init) => {
    const stored = als.getStore();
    if (!stored) return origFetch(input, init);
    const req = new Request(input, init);
    if (!req.headers.has(HEADER)) req.headers.set(HEADER, stored);
    return origFetch(req);
  },
});

function unwrap(req) {
  const stored = req.headers.get(HEADER);
  if (!stored) return { stored: null, cleaned: req };
  const h = new Headers(req.headers);
  h.delete(HEADER);
  return { stored, cleaned: new Request(req.url, { method: req.method, headers: h, body: req.body, duplex: req.body ? 'half' : undefined, redirect: 'manual' }) };
}

export default {
  async fetch(req, env, ctx) {
    if (typeof user?.fetch !== 'function') {
      return new Response('user worker has no default.fetch', { status: 500 });
    }
    const { stored, cleaned } = unwrap(req);
    return als.run(stored ?? '', () => user.fetch(cleaned, env, ctx));
  },
  // Re-export other handlers (queue/scheduled/tail/email) wrapped in als.run('')
  // so they don't lose context if they make outbound fetches.
  ...['queue', 'scheduled', 'tail', 'trace', 'email'].reduce((acc, k) => {
    if (typeof user?.[k] === 'function') {
      acc[k] = (...args) => als.run('', () => user[k](...args));
    }
    return acc;
  }, {}),
};
`;
}
